### ISSUE TITLE
Browser tests are broken on Linux

### ISSUE THREAD

**Issue by jessykate** [embassynetwork/modernomad#461] opened 2019-03-01 02:19 UTC
`docker-compose` needs sudo permissions on Linux so are currently broken.

**Comment by bfirsh** [comment] 2019-03-08 16:14
Implementation ideas in #450.

If there isn't some way to automatically detect, I would argue Docker should be the default (because it is recommended dev environment and how it runs in CI) and there should be an option to run outside of Docker.

**Comment by bfirsh** [comment] 2019-03-08 16:15
oops dupe of #458

**Closed by bfirsh** 2019-03-08 16:15 UTC
Labels: Bug
